# Generated by Django 5.1.7 on 2026-06-30 12:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название сети / Юрлица')),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактное лицо')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Профиль магазинов (Сеть)',
                'verbose_name_plural': 'Профили магазинов (Сети)',
                'db_table': 'shop_profiles',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название компании поставщика')),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='Контактное лицо')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Минимальная сумма заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'db_table': 'suppliers',
            },
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='company',
        ),
        migrations.RemoveField(
            model_name='user',
            name='companies',
        ),
        migrations.AlterUniqueTogether(
            name='companyuser',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='user',
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Название конкретной точки')),
                ('address', models.CharField(max_length=500, verbose_name='Фактический адрес')),
                ('is_active', models.BooleanField(default=True, verbose_name='Точка работает')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='api.shopprofile', verbose_name='Родительский профиль/сеть')),
            ],
            options={
                'verbose_name': 'Торговая точка',
                'verbose_name_plural': 'Торговые точки',
                'db_table': 'shops',
            },
        ),
        migrations.CreateModel(
            name='ShopUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_staff', to='api.shop', verbose_name='Закрепленная торговая точка')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shop_users', to='api.role')),
                ('shop_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='api.shopprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сотрудник магазина',
                'verbose_name_plural': 'Сотрудники магазинов',
                'db_table': 'shop_users',
                'unique_together': {('user', 'shop_profile')},
            },
        ),
        migrations.CreateModel(
            name='SupplierUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplier_users', to='api.role')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='api.supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сотрудник поставщика',
                'verbose_name_plural': 'Сотрудники поставщиков',
                'db_table': 'supplier_users',
                'unique_together': {('user', 'supplier')},
            },
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='CompanyUser',
        ),
    ]
